ui: tape
browsers:
  - name: chrome
    version: 39..latest
    platform: Mac 10.10
  - name: safari
    version: 8..latest
    platform: Mac 10.10
  - name: firefox
    version: 34..latest
    platform: Mac 10.10